### ISSUE TITLE
Add link to boxen setup scripts?

### ISSUE THREAD

**Issue by techpeace** [railsgirls/installation-scripts#15]
Hi there! I help organize Rails Girls events in Austin, and I'm also an instructor at a web development training school called MakerSquare. I found myself needing to set up a number of lab and student machines, so I decided to check out [Boxen](http://boxen.github.com/) by the good folks at GitHub. I produced [this simple Boxen setup script](https://github.com/makersquare/student-boxen) for our students which has proven very useful. It installs:
- git
- homebrew
- rbenv
- zsh
- heroku CLI
- SublimeText 2
- iTerm2
- Alfred
- SizeUp
- Chrome
- Firefox
- postgres
- Dropbox
- nodejs
- redis
- wget
- Ruby 2

If any of those are already installed, it detects and skips them (via the magic of Puppet).

Would we like to have something like this for RailsGirls? I know I'll be using it at our next event. If so, I'd be happy to put together a version of the repo on our [RailsGirls ATX org page](http://github.com/railsgirlsatx) that we could fork into the main RailsGirls org.

Thanks!

**Comment by tombruijn** [comment]
The boxen project seems to be archived. Closing.
We have an updated macOS install guide now: https://guides.railsgirls.com/install/macos
