### ISSUE TITLE
Linux install guide/script is super out of date

### ISSUE THREAD

**Issue by lpil** [railsgirls/installation-scripts#23]
We should switch from rvm to rbenv and then Rails 4 and a version of Ruby that hasn't been deprecated.

**Comment by vesan** [comment]
I don't see why we should switch to rbenv but pull requests to update Ruby & Rails would be warmly welcomed.

**Comment by lpil** [comment]
* [rbenv](https://github.com/sstephenson/rbenv) is more popular than [rvm](https://github.com/rvm/rvm)
* rbenv is easier to install and use (and easier to teach) than rvm
* The non-Linux guides already recommend rbenv over rvm. Pretty much all of the OSX guide can be reused if we switch to rbenv for the Linux guide.

On top of that, rvm does some kinda baffling stuff such as overriding `cd`...
