### ISSUE TITLE
rails-install-fedora.sh out of date nodejs install for CentOS 6.6

### ISSUE THREAD

**Issue by rdgRmCore** [railsgirls/installation-scripts#30]
When I tried this install script on CentOS 6.6, it did not successfully install nodejs.

I had to follow these instructions manually after running the install script.

curl --silent --location https://rpm.nodesource.com/setup | bash -
yum -y install nodejs

https://github.com/joyent/node/wiki/installing-node.js-via-package-manager

**Comment by hsbt** [comment]
Unfotunately, CentOS 6 is EOL today.
