### ISSUE TITLE
rails isn't installed

### ISSUE THREAD

**Issue by natesire** [railsgirls/installation-scripts#41]
I am trying the Ubuntu install. Rails isn't being installed. Is the project still being maintained. I can help look into this.

**Comment by vesan** [comment]
It should work. What kind of error message are you getting?

**Comment by dataguy2020** [comment]
I think rbenv global 2.2.3 command needs run. Ruby just isn't showing up as a command.

**Comment by tombruijn** [comment]
I've updated the install script in https://github.com/railsgirls/installation-scripts/pull/64
Works on the latest Ubuntu again.
