### ISSUE TITLE
Change NodeJS repository to Node Source from Chris Lea

### ISSUE THREAD

**Issue by mtomov** [railsgirls/installation-scripts#42]
The Chris Lea repository has been deprecated in favour of the one at Node Source. See info:
- https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions
- https://nodesource.com/blog/chris-lea-joins-forces-with-nodesource/

It will be nice to update the script to reflect this change.

**Comment by vesan** [comment]
Seems like a solid change! Please send a pull request for the change and I'll merge.

**Comment by mtomov** [comment]
: ) I was hoping that someone else would be up for doing the change itself : )

Thanks for the prompt reply!
