### ISSUE TITLE
Ubuntu script does not yet support Cosmic Cuttlefish during node installation

### ISSUE THREAD

**Issue by ericpoe** [railsgirls/installation-scripts#52]
Using Ubuntu 18.10 (aka "Cosmic Cuttlefish")

While running the install script, I get the following error:

> \#\# Confirming "cosmic" is supported...
>
>\+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_6.x/dists/cosmic/Release'
>
>\#\# Your distribution, identified as "cosmic", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

As can be seen at the following locations, at this time of this ticket, only Node 10 is supported.

- https://deb.nodesource.com/node_6.x/dists/
- https://deb.nodesource.com/node_8.x/dists/
- https://deb.nodesource.com/node_10.x/dists/

It appears that node 8 ships in the standard Ubuntu repositories, so it is not provided in nodesource.com at this time. No idea about why node 6 isn't available. See: https://github.com/nodesource/distributions/issues/740

As an alternative, node can be installed via `snap`, which is included with Ubuntu 16.04 and later.

**Comment by vesan** [comment]
I think we should update to Node 10 in the install script. Node 6 support is ending in less than a year (April 2019) and I think everything should work with Node 10 just fine.

**Comment by tombruijn** [comment]
Fixed in the updated script. https://github.com/railsgirls/installation-scripts/pull/64
